### ISSUE TITLE
两个兼容性问题

### ISSUE THREAD

**Issue by ThinkLoudly** [msmbps/msmbps#2]
1. 我在 Firefox 61 中测试发现[误差较大](https://user-images.githubusercontent.com/6403177/42136346-3af2d5f8-7d51-11e8-8201-49b76b774e9b.png)，@codehz 修改前的版本[稍好些](https://user-images.githubusercontent.com/6403177/42136352-697ec8aa-7d51-11e8-9559-b2fe53a5e190.png)，但也跟 Chrome 中差很多
2. `Object.entries()`[不支持 IE 和 iOS Safari](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Browser_compatibility)

**Comment by codehz** [comment]
Entries理论上可以polyfill ( 
误差的问题，涉及浏览器本身的实现，很难解决
不过http ping我想到的应用场景要么是比较哪个机房更好，要么是测试网页响应的速度（就是那种开网站的，这点来说，也没有问题，不同浏览器不一样的情况符合预期

**Comment by codehz** [comment]
误差的话，我觉得无解（

**Comment by ThinkLoudly** [comment]
谢谢回复。

根据 https://jsperf.com/object-keys-vs-for-in-with-closure/111 ，我觉得误差大主要是 Object.entries 造成的，虽然 pingms 的早期实现粗暴些，但确实误差小。

当然，如你所说，根据使用场景，这误差或许没那么重要。那这 issue 我就关了。

**Comment by msmbps** [comment]
@ThinkLoudly 老版本偶尔误差偏大，原因是“抖动”（网络和浏览器的不稳定性）。相对而言，Firefox的“抖动”可能更多。最新版本已经解决了这个问题（多个HTTP请求测试一个目标服务器）。iOS Safari可以正常运行代码，已经测试过了（Mozilla文档不准确）。然后代码没有支持IE，因为IE用户已经很少了。

@codehz JS代码做了许多改动，如果有时间，请查看一下是否有bug。
